name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm install
        
    - name: Run tests with coverage
      run: npm run test:coverage
      
    - name: Check coverage threshold
      uses: actions/checkout@v2
      run: |
        COVERAGE=$(cat coverage/coverage.json | jq '.total.statements.pct')
        if (( $(echo "$COVERAGE < 50" | bc -l) )); then
          echo "Code coverage is below 50%: $COVERAGE%"
          exit 1
        else
          echo "Code coverage is at least 50%: $COVERAGE%"
        fi
